YAKU_JA = {
    "Aka Dora": "赤ドラ",
    "Chankan": "槍槓",
    "Chanta": "混全帯ヤオ九",
    "Chiitoitsu": "七対子",
    "Chinitsu": "清一色",
    "Yakuhai (chun)": "役牌(中)",
    "Double Riichi": "ダブル立直",
    "Dora": "ドラ",
    "Yakuhai (east)": "役牌(東)",
    "Haitei Raoyue": "海底撈月",
    "Yakuhai (haku)": "役牌(白)",
    "Yakuhai (hatsu)": "役牌(發)",
    "Honitsu": "混一色",
    "Honroutou": "混老頭",
    "Houtei Raoyui": "河底撈魚",
    "Iipeiko": "一盃口",
    "Ippatsu": "一発",
    "Ittsu": "一気通貫",
    "Junchan": "純全帯ヤオ九",
    "Nagashi Mangan": "流し満貫",
    "Yakuhai (north)": "役牌(北)",
    "Pinfu": "平和",
    "Renhou": "人和",
    "Riichi": "立直",
    "Rinshan Kaihou": "嶺上開花",
    "Ryanpeikou": "二盃口",
    "San Ankou": "三暗刻",
    "San Kantsu": "三槓子",
    "Sanshoku Doujun": "三色同順",
    "Sanshoku Doukou": "三色同刻",
    "Shou Sangen": "小三元",
    "Yakuhai (south)": "役牌(南)",
    "Tanyao": "断ヤオ九",
    "Toitoi": "対々和",
    "Menzen Tsumo": "門前清自摸和",
    "Yakuhai (west)": "役牌(西)",
    "Yakuhai (wind of place)": "役牌(自風)",
    "Yakuhai (wind of round)": "役牌(場風)",
    "Chiihou": "地和",
    "Chinroutou": "清老頭",
    "Chuuren Poutou": "九蓮宝燈",
    "Daburu Chuuren Poutou": "純正九蓮宝燈",
    "Kokushi Musou Juusanmen Matchi": "国士無双十三面待ち",
    "Daisangen": "大三元",
    "Dai Suushii": "大四喜",
    "Kokushi Musou": "国士無双",
    "Ryuuiisou": "緑一色",
    "Shousuushii": "小四喜",
    "Suu ankou": "四暗刻",
    "Suu ankou tanki": "四暗刻単騎",
    "Suu kantsu": "四槓子",
    "Tenhou": "天和",
    "Tsuu iisou": "字一色",
}
